# Generated by Django 3.2.19 on 2023-10-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lesson', models.CharField(max_length=200)),
                ('time_of_lesson', models.DateTimeField()),
            ],
        ),
    ]
