# Generated by Django 3.2.19 on 2023-10-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit_sync_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduled_lessons_main',
            name='created_for_user',
        ),
        migrations.AlterField(
            model_name='scheduled_lessons_main',
            name='created_by_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
