# Generated by Django 3.2.19 on 2023-10-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit_sync_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_here',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lesson', models.CharField(max_length=200)),
                ('time_of_lesson', models.DateTimeField()),
                ('created_by_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
