# Generated by Django 3.2.19 on 2023-10-19 09:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_sync_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_of_lesson',
            name='cretaed_for_user',
            field=models.CharField(default=0, max_length=256, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
