# Generated by Django 3.2.19 on 2023-11-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_sync_app', '0002_trainingsession_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='number',
            new_name='price',
        ),
    ]
