# Generated by Django 3.2.19 on 2023-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_sync_app', '0002_rename_schedule_a_lesson_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_a_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lesson', models.CharField(max_length=200)),
                ('time_of_lesson', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
