# Generated by Django 3.2.19 on 2023-10-15 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit_sync_app', '0002_create_here'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_here',
            new_name='schedule_of_lesson',
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
