# Generated by Django 3.2.19 on 2023-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_sync_app', '0003_rename_number_trainingsession_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=200),
        ),
    ]
