# Generated by Django 3.2.19 on 2023-12-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit_sync_app', '0005_alter_trainingsession_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('cancelled', 'cancelled')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
