# Generated by Django 3.2.19 on 2023-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_sync_app', '0007_alter_trainingsession_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='pending', max_length=200),
        ),
    ]
