# Generated by Django 3.2.19 on 2023-12-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_sync_app', '0008_alter_trainingsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='pending', max_length=200),
        ),
    ]
